Memuat dataset

https://www.kaggle.com/datasets/uciml/iris

In [1]:
import pandas as pd
#TAHAPAN 1 IMPORT DATA
df = pd.read_csv('Iris.csv') 
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Melihat Nlai yang kosong

In [2]:
# Melihat missing value
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

Data Reduction

In [3]:
# Memisahkan variabel dan class
X = df.drop(['Id', 'Species'], axis=1) 
y = df[['Species']]
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

Memilah Data Training dan Testing

In [6]:
# Split Data Training = 70% dan Data Testing 30%
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, 
y, test_size = 0.3, random_state=0)
print(X_train.shape, y_train.shape) 
print(X_test.shape, y_test.shape)

(105, 4) (105, 1)
(45, 4) (45, 1)

Membuat Model Random Forest

In [10]:
# Training Model Random Forest
from sklearn.ensemble import RandomForestClassifier 
#create a classifier
model = RandomForestClassifier(n_estimators=40) 
#train the model
modelfit = model.fit(X_train, y_train.values.ravel()) 
accuracy = modelfit.score(X_test, y_test.values.ravel())
#predict the response
y_pred = model.predict(X_test)
print(accuracy)

0.9777777777777777

Mengevaluasi Model

In [11]:
# Evaluasi model dengan confusion matrix
from sklearn.metrics import classification_report 
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.94      0.97        18
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.98        45
      macro avg       0.97      0.98      0.98        45
   weighted avg       0.98      0.98      0.98        45

Import model ke File pickle

In [14]:
import pickle
with open('randomforet_pickle','wb') as r: 
    pickle.dump(modelfit,r)